### ISSUE TITLE
LocatorAssertions#to_be_in_viewport does not work

### ISSUE THREAD

**Issue by YusukeIwaki** [YusukeIwaki/playwright-ruby-client#324]
### Step To Reproduce / Observed behavior

```
RSpec.describe 'app' do
  include Playwright::Test::Matchers

  it 'should work' do
    visit '/login'
    fill_in 'username', with: 'admin'
    fill_in 'password', with: 'password!'
    click_button 'ログイン'

    page.driver.with_playwright_page do |page|
      expect(page.get_by_text('ADMIN')).to be_in_viewport
      expect(page.get_by_text('お知らせ')).to be_in_viewport
    end
  end
end
```

```
Failures:

  1) app should work
     Failure/Error: expect(page.get_by_text('ADMIN')).to be_in_viewport
     
     Playwright::Error:
       expectedNumber: expected number, got object
     # ./spec/app_playwright_spec.rb:15:in `block (3 levels) in <top (required)>'
     # ./spec/app_playwright_spec.rb:14:in `block (2 levels) in <top (required)>'
```

`to_be_visible` works as expected. `to_be_in_viewport` is buggy.

### Expected behavior

test passes.
